config/routes.rb
DonorsChooseWireframe::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  resources :projects do
    resources :messages
    resources :challenges, except: :index do
      resources :challenge_evidences
    end
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match "/projects/:id/challenges" => redirect("/projects/%{id}/challenges/new")
  delete 'sessions/destroy'

  root to: 'projects#new'
end

app/models/project.rb
require 'donors_choose'
class Project < ActiveRecord::Base
  attr_protected :id
  has_many :challenges
  has_many :messages
  has_many :events
  monetize :amount_raised_cents, allow_nil: true

  after_create :sanitize_data

  def self.valid_url(url)
    return true unless DonorsChooseApi::Project.find_by_url(url) ==
      "Invalid Donors Choose Url"
  end

  def self.from_donors_choose_url(url)
    dc_id = donors_choose_id_from_url(url)
    self.find_or_initialize_by_donors_choose_id(dc_id)
  end

  def set_attrs_from_donors_choose(url)
    self.attributes = donors_choose_attributes
    save
  end

  def refresh_donors_choose_data
    self.attributes = donors_choose_attributes
    save
  end

  def cents_to_complete
    (cost_to_complete.to_f * 100).to_i
  end

  def raised_to_date
    calculate_amount_raised_cents unless amount_raised
    amount_raised
  end

  def currency_to_complete
    Money.new(cents_to_complete)
  end

  def currency_total_price
    Money.new(total_price.to_f*100)
  end

  private

  def donors_choose_attributes
    DonorsChooseApi::Project.find_by_id(self.donors_choose_id).attributes
  end

  def self.donors_choose_id_from_url(url)
    url.scan(/\d{4,}/).first
  end

  def calculate_amount_raised_cents
    self.amount_raised_cents = ((total_price.to_f - cost_to_complete.to_f) *
      100).to_i
    save
  end

  def sanitize_data
    attributes.each do |attr|
      attributes[attr] = HTMLEntities.new.decode(attr)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @projects = Project.limit(10)
    @project = Project.new
  end

  def create
    url = params[:project][:proposal_url]
    if Project.valid_url(url)
      project = Project.from_donors_choose_url(url)
      if project.new_record?
        project.set_attrs_from_donors_choose(url)
        redirect_to new_project_challenge_path(:project_id => project.id)
        flash[:notice] = "Thanks for adopting this project! To kick this party
          off right, create a new challenge!"
      else
        redirect_to project_path(project)
        flash[:notice] = "This project already exists. You can contribute
         to it here!"
      end
    else
      redirect_to root_path
      flash[:error] = "Sorry, we are unable to match the URL with a
       Donors Choose project"
    end
  end

  def show
    @project = Project.find(params[:id])
    @challenges = Challenge.where("project_id = ?",
                                  params[:id]).order("amount ASC").limit(6)
  end

  def index
    @projects = Project.where(:funding_status => "needs funding").order(
      "title").page(params[:page]).per(8)
  end
end

app/views/projects/_all_projects.html.erb
<% @projects.each do |project| %>
	<li class="project-info">
		<div id="project-title">
    	<%= project.title %>
  	</div>
  	<div class="image">
			<%= link_to image_tag(project.image_url), project_path(project) %>
		</div>
	</li>
<% end %>

app/views/projects/_challenge_header.html.erb
<h1 class="sixcol">Featured Challenge</h1>
<h1 class="sixcol last">Other challenges for this project:</h1>

app/views/projects/_challenge_nav_tab.html.erb
<div class="challenge-nav-tab-contents">
  <a class="nav-tab-link" href="#tab<%=challenge.id%>" data-toggle="tab"></a>
<div class="row any-width">
  <div class="twocol">
    <div class="at-price">At <%= humanized_money_with_symbol challenge.target_funding %></div>
  </div>
  <div class="twocol">
    <a class="nav-tab-link" href="#tab<%=challenge.id%>" data-toggle="tab">
      <%= image_tag(challenge.display_media) %>
    </a>
  </div>
  <div class="sixcol last">
    <span class="challenge-nav-text"><span class="challenge-username"><%= challenge.name %></span> will: <%= challenge.title %></span>
    <div>
      <%= link_to("View Challenge", project_challenge_path(@project, challenge), class: "challenge-link")  %>
    </div>
  </div>
</div>
</div>

app/views/projects/_challenge_nav_tabs.html.erb
<ul class="feed-challenges nav nav-tabs">
  <li class="feed-challenge active" id="feed-challenge-<%=challenges.first.id%>">
    <%= render partial: "challenge_nav_tab", locals: {challenge: challenges.first} %>
  </li>

  <% challenges[1..-1].each do |challenge| %>
    <li class="feed-challenge" id="feed-challenge-<%=challenge.id%>">
      <%= render partial: "challenge_nav_tab", locals: {challenge: challenge} %>
    </li>
  <% end %>
</ul>

app/views/projects/_challenge_tab.html.erb
<div class="row any-width">
  <div class="twelvecol featured-challenge-image">
    <%= link_to(image_tag(challenge.display_media), project_challenge_path(@project, challenge))  %>
  </div>
</div>

<div class="row any-width">
  <div class="challenger twocol">
    <div class="challenger-image">
      <%= image_tag(challenge.owner_avatar) %>
    </div>
    <span class="user-name"><%= link_to challenge.name, "#" %></span>
  </div>

  <div class="challenge-description sixcol">
    <div>
      Will <span class="challenge-action"><%= challenge.title %></span>
    </div>
  </div>

  <div class="fourcol last">
    <div class="challenge-donate">
      <%= link_to "Give", challenge.project.proposal_url, target: "_blank", class: "give-link" %>
    </div>
    <div>
      <%= link_to("View Challenge", project_challenge_path(@project, challenge), class: "challenge-link")  %>
    </div>
  </div>
</div>

app/views/projects/_challenge_tab_contents.html.erb
<div class="challenge-details twelvecol tab-pane active" id="tab<%=@challenges.first.id%>">
  <%= render partial: "challenge_tab", locals: {challenge: @challenges.first} %>
</div>

<% @challenges[1..-1].each do |challenge| %>
  <div class="challenge-details twelvecol tab-pane" id="tab<%=challenge.id%>">
    <%= render partial: "challenge_tab", locals: {challenge: challenge} %>
  </div>
<% end %>

app/views/projects/_featured_challenge.html.erb
<div class="sixcol">
  <div class="featured-challenge">
    <div class="row any-width">
      <% if @challenges.any? %>
        <div class="challenge-details twelvecol">
          <div class="row any-width">
            <h3>This challenge has almost met its goal — Push it over the edge by making a donation!</h3>
          </div>
          <div class="row any-width">
            <div class="twelvecol featured-challenge-image">
              <%= link_to(image_tag(@challenges.first.display_media), project_challenge_path(@project, @challenges.first))  %>
            </div>
          </div>
          <div class="row any-width">
            <div class="challenger twocol">
              <div class="challenger-image">
                <img src="https://si0.twimg.com/profile_images/1373765588/Verdi_reasonably_small.jpg">
              </div>
              <span class="user-name"><%= link_to @challenges.first.name, "#" %></span>
            </div>
            <div class="challenge-description sixcol">
              <div>
                <span class="challenge-will">WILL:</span>
                <span class="challenge-action"><%= @challenges.first.title %></span>
              </div>
              <div>
                <span class="challenge-if">IF:</span><span class="challenge-condition">the project reaches $<%= @challenges.first.amount %></span>
              </div>
            </div>
            <div class="fourcol last">
              <div class="challenge-money">
                <div class="challenge-progress">
                  <span class="dollars-left">$84</span>
                  <p class="to-go">To Go</p>
                </div>
                <div class="challenge-donate">
                  <%= link_to "Give", @challenges.first.project.fund_url, class: "give-link" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_how_to_use.html.erb
<hr>

<div class="row how-to-row">
  <div class="fivecol">
    <%= image_tag("images/how-to-1.png") %>
  </div>
  <div class="onecol splash-icon-wrap">
    <span class="icon splash-icon">
      &#060;AA
    </span>
  </div>
  <div class="fivecol last">
    <div class="info-details">
      <span class="number">1.</span> Find a <a href="http://www.donorschoose.org/" target="blank">Donor's Choose</a> project you'd like to support. Find one on their site or pick from our <%= link_to "list", projects_path %>.
    </div>
  </div>
</div>

<hr>
<div class="row how-to-row">
  <div class="fivecol">
    <div class="info-details">
      <p><span class="number">2.</span> Challenge the world by posting a task you'll perform when the project reaches a funding goal.</p>
      <p><span class="bold">Community service</span> to <span class="bold">egregious facial hair</span> -- Anything Goes!</p>
    </div>
  </div>
  <div class="onecol splash-icon-wrap">
    <span class="icon splash-icon">
      AA=
    </span>
  </div>
  <div class="fivecol last">
    <%= image_tag("images/how-to-2.png") %>
  </div>
</div>

<hr>
<div class="row how-to-row">
  <div class="fivecol">
    <%= image_tag("images/how-to-3.png") %>
  </div>
  <div class="onecol splash-icon-wrap">
    <span class="icon splash-icon">
      &#060;AA
    </span>
  </div>
  <div class="fivecol last">
    <div class="info-details">
      <span class="number">3.</span> Goad your friends and family to donate! Your loss will be the gain of children across the country.
    </div>
  </div>
</div>

<hr>
<div class="row how-to-row">
  <div class="fivecol">
    <div class="info-details">
      <span class="number">4.</span> Post evidence to prove you're legit. (Positive reinforcement will keep 'em coming back for more)
    </div>
  </div>
  <div class="onecol splash-icon-wrap">
    <span class="icon splash-icon">
      AA=
    </span>
  </div>
  <div class="fivecol last">
    <%= image_tag("images/how-to-4.png") %>
  </div>
</div>

app/views/projects/_new_project_form.html.erb
  <div class="row">
    <div class="twelvecol tagline tagline-name">
      <h1><span class="site-name">Donors Challenge:</span>
    </div>
  </div>

  <div class="row">
    <div class="twelvecol tagline tagline-copy">
      <h2>Raising money at the expense of your dignity.</h2>
    </div>
  </div>

  <div class="well">
    <div class="project-creation">
      <h1 class="title">Choose a Project</h1>
      <div class="row">
        <div class="twelvecol">
          <h2 class="project-cta">Find a Donors Choose Project you'd like to support and enter the URL below:</h2>
        </div>
      </div>
      <div class="row">
          <%= form_for @project do |f| %>
            <div class="ninecol">
              <%= f.text_field :proposal_url, placeholder: "Enter a Donors Choose URL (e.g. http://www.donorschoose.org/project/comfy-literacy-center/814936/)", class: 'text_field' %>
            </div>
            <div class="threecol last">
              <%= f.submit class: 'form-submit', value: "Adopt Project" %>
            </div>
          <% end %>
      </div>

    <h2 class="title-padding"> Or </h2>

      <div class="row project-form-header">
        <div class="twelvecol">
          <h2 class="project-cta">Support a project that has already been adopted:</h2>
        </div>
      </div>
      <div class="row sample-projects" id="sample-projects">
        <% @projects[0..3].each do |project| %>
          <div class="threecol" id="project_info">
            <div id="project-title-2">
              <%= project.title %>
            </div>
            <div class="image">
              <%= link_to image_tag(project.image_url), project_path(project) %>
            </div>
          </div>
        <% end %>
        <div class="project-link">
          <%= link_to "Click here for a full list of adopted projects", projects_path %> 
        </div>
      </div>
    </div>
  </div>

  <div id="how-to-use">
    <%= render partial: "how_to_use" %>
  </div>

app/views/projects/_other_challenges.html.erb
<div class="active-challenges sixcol last">
  <div class="feed-challenges">
    <% @challenges.each do |challenge| %>
      <div class="feed-challenge" id="feed-challenge-<%=challenge.id%>">
        <div class="row any-width">
          <div class="twocol">
            <%= link_to(image_tag(challenge.display_media), project_challenge_path(@project, challenge))  %>
          </div>
          <div class="tencol last">
            <span class="challenge-feed-name">
              <%= challenge.name %> will:
            </span>
            <span class="challenge-feed-title">
              <%= challenge.title %>
            </span>
            <div class="challenge-feed-target">
              When the project raises <%= humanized_money_with_symbol challenge.target_funding %>! <span class="amount-remaining">(Only <%= humanized_money_with_symbol challenge.amount_currency %> to go!)</span>

            </div>
            <div>
            <%= link_to("View Challenge", project_challenge_path(@project, challenge), class: "challenge-link")  %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/projects/_other_challenges_bar.html.erb
<div id="other-challenges">
  <div class="row any-width">
    <div class="eightcol">
      <h1>Other Challenges</h1>
    </div>
    <div class="fourcol last">
      <div class="new-challenge-link">
        <%= link_to "Create New Challenge", new_project_challenge_path(:project_id => @project.id) %>
      </div>
    </div>
  </div>
  <div id="challenge-list">
    <div class="row any-width">
      <div class="fourcol challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
      <div class="fourcol challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
      <div class="fourcol last challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
      <div class="fourcol challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
      <div class="fourcol challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
      <div class="fourcol last challenge-preview">
        <p>A message here</p>
        <img class="challenge-thumbnail" src="http://projectkong.files.wordpress.com/2009/07/slackline1.jpg">
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
	
  <div class="row spacer"></div>

	<div class="well">
	  <div class="twelvecol">
	  	<h1 id="index-title">Current Adopted Projects</h1>
	  	<ul class="all-projects">
		  	<%= render :partial => "all_projects" %>
			<div class="pagination">
				<%= paginate @projects %>
			</div>
		</ul>

	  </div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row spacer"></div>

  <div class='row'>
    <%= render partial: "new_project_form" %>
  </div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row spacer"></div>

    <div class="row">
      <div class="twelvecol">
        <h1><span class="highlight">Challenges for:</span> <%= link_to @project.title.html_safe, @project.proposal_url, target: "_blank"%> </h1>
      </div>
    </div>

    <div class="row spacer"></div>
    <div class="row">
      <div id="progress-box" class="sixcol">
        <% if @project.percent_funded == "0" %>
          <div class="meter">
            No donations have been made yet
          </div>
        <% else %>
          <div class="meter orange">
            <span style="width: <%= @project.percent_funded.to_i %>%"><span class="bar-font"><%= humanized_money_with_symbol @project.raised_to_date %></span></span>
          </div>
        <% end %>
      </div>
      <div class="give-bar">
        <div class="twocol">
            <%= humanized_money_with_symbol @project.raised_to_date %> <span class="small">raised</span>
        </div>
        <div class="twocol">
          <%= humanized_money_with_symbol @project.cost_to_complete %> <span class="small">to go</span>
        </div>
        <div class="twocol last">
          <%= link_to "Give", @project.proposal_url, target: "_blank", class: "give-link-big" %>
        </div>
      </div>
    </div>

  <div class="challenges">
    <div class="row">

    <div class="tabbable tabs-left"> <!-- Only required for left/right tabs -->
      <div class="active-challenges sixcol">
        <% if @challenges.any? %>
          <%= render partial: "challenge_nav_tabs", locals: {challenges: @challenges} %>
        <% end %>
        <div class="new-challenge-link">
          <%= link_to "Make Your Own Challenge!", new_project_challenge_path(:project_id => @project.id) %>
        </div>
      </div>

      <div class="sixcol last">
        <div class="featured-challenge">
          <div class="row any-width">
            <div class="tab-content">
              <% if @challenges.any? %>
                <%= render partial: "challenge_tab_contents", locals: {challenges: @challenges} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- end tabbable tabs-right -->
  </div> <!-- end challenges -->
  <div class="row spacer"></div>
  <div class="row spacer"></div>
  <div class="row spacer"></div>
  <div class="row spacer"></div>
  <div class="row spacer"></div>
</div> <!--end container -->