config/routes.rb
DonorsChooseWireframe::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  resources :projects do
    resources :messages
    resources :challenges, except: :index do
      resources :challenge_evidences
    end
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match "/projects/:id/challenges" => redirect("/projects/%{id}/challenges/new")
  delete 'sessions/destroy'

  root to: 'projects#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donors Challenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="custom-container" id="navbar">
    <div class="row header">
      <div class="twelvecol">
        <h1 class="brand">
          <%= link_to "Donors Challenge", root_path %>
          <span id="user-links">
            <% if current_user %>
              <%= current_user.name %> |
              <%= link_to "Sign out", sessions_destroy_path, method: :delete %>
            <% else %>
              <%= link_to "Sign in with Twitter", '/auth/twitter' %>
            <% end %>
          </span>
        </h1>
      </div>
    </div>
  </div> <!-- navbar -->

  <div id="page-container">
    <div class="flash-container container">
      <div class="row flash-row">
       <% if flash[:notice] %>
          <p class="alert alert-success"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:error] %>
          <p class="alert alert-error"><%= flash[:error] %></p>
        <% end %>
      </div>
    </div>

    <%= yield %>
  </div>

</body>
</html>